# Generated by Django 3.0.6 on 2020-05-18 10:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resumebuilder', '0003_auto_20200518_1602'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resume',
            name='create_date',
            field=models.DateTimeField(null=True),
        ),
    ]
