# Generated by Django 3.0.6 on 2020-05-18 10:42

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('resumebuilder', '0005_auto_20200518_1608'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='resume',
            name='create_date',
        ),
        migrations.AddField(
            model_name='resume',
            name='created_on',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
